Repository Lets-Be-Friendly-Team/daeng-ggu-frontend, pull requests merged in 2024-11, with the labels that each got.

#9 프로필 이미지 컴포넌트 구현
  packages/design-system/assets/images/logoImage.png
  packages/design-system/components/ProfileImage/UserProfileImage.tsx
  packages/design-system/index.ts
  packages/design-system/types/images.d.ts
Labels: 🛠️ 기능

#18 카테고리탭 수정, 헤더 수정, 견적요청 로직 대강완료
  apps/owner/src/pages/Request/Request.tsx
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Request/Test.tsx
  apps/owner/src/pages/Status/CompletedRequest.tsx
  apps/owner/src/pages/Status/PendingRequest.tsx
  apps/owner/src/pages/Status/Status.tsx
  apps/owner/src/router.tsx
  apps/owner/src/styles/sequenceAnimation.css
  apps/owner/tailwind.config.js
  packages/design-system/components/BorderContainer/BorderContainer.tsx
  packages/design-system/components/CategoryTab/CategoryTab.tsx
  packages/design-system/components/Header/Header.tsx
Labels: 🚀 개선, 🛠️ 기능

#20 아바타 컴포넌트 구현
  apps/owner/src/pages/MainPage/MainPage.tsx
  packages/design-system/components/Avatar/Avatar.tsx
  packages/design-system/components/Icons/PlusIcon.tsx
  packages/design-system/index.ts
Labels: 🛠️ 기능

#22 lint 설정 수정
  .yarn/install-state.gz
  apps/guardian/package.json
  apps/owner/package.json
  apps/owner/src/pages/MainPage/MainPage.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Request/Test.tsx
  apps/owner/src/pages/index.ts
  apps/storybook/src/stories/Button.tsx
  apps/storybook/src/stories/Header.tsx
  eslint.config.js
  package.json
  packages/design-system/.eslintrc.cjs
  packages/design-system/components/TypeOneButton/TypeOneButton.tsx
  packages/design-system/eslint.config.js
  packages/design-system/index.ts
  packages/design-system/lib/utils.ts
  packages/design-system/package.json
  packages/design-system/vite.config.ts
  yarn.lock
Labels: 🐞 버그, 🚀 개선, 🍪 배포

#24 스토리북 스크립트 수정
  .github/workflows/storybook-gh-pages.yml
  apps/storybook/.gitignore
  apps/storybook/eslint.config.js
  apps/storybook/package.json
Labels: 🚀 개선, 🍪 배포

#25 주소 입력창 컴포넌트 구현
  apps/owner/src/pages/AddressTest/AddressTest.tsx
  apps/owner/src/router.tsx
  package.json
  packages/design-system/components/Icons/MySearchIcon.tsx
  packages/design-system/components/Input/Input.tsx
  packages/design-system/components/InputAddress/InputAddress.tsx
  packages/design-system/components/InputAddress/SearchAddress.tsx
  packages/design-system/index.ts
  packages/design-system/tsconfig.json
  packages/design-system/utils/getAddress.ts
  yarn.lock
Labels: 🛠️ 기능

#27 스토리북 배포 수정 및 디자인 시스템 상대경로 설정
  .github/workflows/storybook-gh-pages.yml
  .yarn/install-state.gz
  apps/storybook/.storybook/preview.ts
  apps/storybook/package.json
  apps/storybook/postcss.config.js
  apps/storybook/src/stories/Calendar/Calendar.stories.ts
  apps/storybook/src/styles/index.css
  apps/storybook/tailwind.config.js
  apps/storybook/tsconfig.app.json
  eslint.config.js
  package.json
  packages/design-system/components/RadioGroup/RadioGroup.tsx
  packages/design-system/components/SearchBar/SearchBar.tsx
  packages/design-system/package.json
  packages/design-system/tsconfig.json
  yarn.lock
Labels: 🐞 버그, 🚀 개선, 🍪 배포

#28 사용자 견적 조회 페이지 초안 구현, 상세보기 미구현
  .yarn/install-state.gz
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Status/CompletedRequest.tsx
  apps/owner/src/pages/Status/EmptyState.tsx
  apps/owner/src/pages/Status/PendingRequest.tsx
  apps/owner/src/pages/Status/RequestContainer.tsx
  apps/owner/src/pages/Status/Status.tsx
  packages/design-system/components/Avatar/Avatar.tsx
  packages/design-system/components/Icons/MySearchIcon.tsx
  packages/design-system/components/Icons/ReportDangIcon.tsx
  packages/design-system/components/InputAddress/SearchAddress.tsx
  yarn.lock
Labels: 🚀 개선, 🛠️ 기능

#29 견종 선택을 위한 체크 박스 및 라디오 컴포넌트 구현
  packages/design-system/assets/images/bichon.webp
  packages/design-system/assets/images/husky.webp
  packages/design-system/assets/images/red-poodle.webp
  packages/design-system/assets/images/shiba-inu.webp
  packages/design-system/components/DogTypePicker/DogTypePicker.tsx
  packages/design-system/index.ts
  packages/design-system/types/image.d.ts
  packages/design-system/types/images.d.ts
Labels: 🛠️ 기능

#31 날짜에 대한 정규표현식 추가 및 기타 디자인 추가
  apps/owner/src/pages/Status/CompletedRequest.tsx
  apps/owner/src/pages/Status/PendingRequest.tsx
  apps/owner/src/pages/Status/RequestContainer.tsx
  apps/owner/src/pages/Status/Status.tsx
Labels: 🚀 개선, 🛠️ 기능

#33 yarn.lock 업데이트
  .yarn/install-state.gz
  apps/owner/src/main.tsx
  packages/design-system/components/Calendar/Calendar.tsx
  yarn.lock
Labels: 🐞 버그, 🍪 배포

#35 서비스 선택을 위한 체크박스 컴포넌트 구현
  packages/design-system/components/Avatar/Avatar.tsx
  packages/design-system/components/Icons/ArrowDown.tsx
  packages/design-system/components/Icons/ArrowUp.tsx
  packages/design-system/components/Icons/BackIcon.tsx
  packages/design-system/components/Icons/BellAlertIcon.tsx
  packages/design-system/components/Icons/CheckedIcon.tsx
  packages/design-system/components/Icons/CloseIcon.tsx
  packages/design-system/components/Icons/PlusIcon.tsx
  packages/design-system/components/Icons/ReportDangIcon.tsx
  packages/design-system/components/Icons/UncheckedIcon.tsx
  packages/design-system/components/ServiceCheckBox/ServiceCheckBox.tsx
  packages/design-system/index.ts
Labels: 🛠️ 기능

#36 layout padding 추가
  apps/owner/src/App.tsx
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  packages/design-system/components/BottomTabBar/BottomTabBar.tsx
  packages/design-system/components/Layout/Layout.tsx
Labels: 🚀 개선, 🛠️ 기능

#38 refactor: 주소 입력창 컴포넌트 props 추가
  apps/owner/src/pages/AddressTest/AddressTest.tsx
  packages/design-system/components/InputAddress/InputAddress.tsx
  packages/design-system/components/InputAddress/SearchAddress.tsx
Labels: 🚀 개선
