Repository Lets-Be-Friendly-Team/daeng-ggu-frontend, pull requests merged in 2024-12, with the labels that each got.

#40 상세페이지 컴포넌트화 및 라우터 개선
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/pages/Request/ProfileViewer.tsx
  apps/owner/src/pages/Request/Request.tsx
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Status/CompletedRequest.tsx
  apps/owner/src/pages/Status/DetailPage.tsx
  apps/owner/src/pages/Status/PendingRequest.tsx
  apps/owner/src/pages/Status/Status.tsx
  apps/owner/src/router.tsx
  apps/owner/src/styles/sequenceAnimation.css
  packages/design-system/components/BorderContainer/BorderContainer.tsx
  packages/design-system/components/DetailButton/DetailButton.tsx
  packages/design-system/components/Icons/RightIcon.tsx
  packages/design-system/components/Icons/right.svg
  packages/design-system/index.ts
Labels: 🚀 개선, 🛠️ 기능

#42 이미지 업로드 컴포넌트 구현
  .yarn/install-state.gz
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/pages/InputTest/InputTest.tsx
  package.json
  packages/design-system/assets/images/logoImage.png
  packages/design-system/components/FileUploader/ImageSlider.tsx
  packages/design-system/components/FileUploader/ImageUploader.tsx
  packages/design-system/components/FileUploader/ProfileImgUploader.tsx
  packages/design-system/components/FileUploader/swiperStyles.css
  packages/design-system/components/Icons/CameraIcon.tsx
  packages/design-system/components/Icons/CloseCircleIcon.tsx
  packages/design-system/index.ts
  yarn.lock
Labels: 🛠️ 기능

#43 이미지 업로드 수정
  apps/owner/src/pages/InputTest/InputTest.tsx
  packages/design-system/components/FileUploader/ImageSlider.tsx
  packages/design-system/components/FileUploader/ImageUploader.tsx
  packages/design-system/components/FileUploader/ProfileImgUploader.tsx
  yarn.lock
Labels: 🚀 개선

#48 견적 조회 로직 완, ts 폴더 구성
  .yarn/install-state.gz
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Request/Test.tsx
  apps/owner/src/pages/Status/CompletedRequest.tsx
  apps/owner/src/pages/Status/CompletedRequestDesigner.tsx
  apps/owner/src/pages/Status/CompletedRequestUser.tsx
  apps/owner/src/pages/Status/DetailPage.tsx
  apps/owner/src/pages/Status/PendingRequest.tsx
  apps/owner/src/pages/Status/PendingRequestDesigner.tsx
  apps/owner/src/pages/Status/PendingRequestReservation.tsx
  apps/owner/src/pages/Status/PendingRequestUser.tsx
  apps/owner/src/pages/Status/Status.tsx
  apps/owner/src/pages/Status/Temp.tsx
  apps/owner/src/router.tsx
  apps/owner/src/sentry.ts
  apps/owner/src/types/requestAndStatusTypes.ts
  packages/design-system/components/Avatar/Avatar.tsx
Labels: 🚀 개선, 🛠️ 기능

#49 리뷰 상세 페이지 구현
  .yarn/install-state.gz
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
  apps/owner/src/pages/EditPetProfilePage/EditPetProfilePage.tsx
  apps/owner/src/pages/EditUserProfilePage/EditUserProfilePage.tsx
  apps/owner/src/pages/MyPage/MyPage.tsx
  apps/owner/src/pages/MyPage/components/AvartarList.tsx
  apps/owner/src/pages/MyPage/components/BookmarkItem.tsx
  apps/owner/src/pages/MyPage/components/BookmarkList.tsx
  apps/owner/src/pages/MyPage/components/Profile.tsx
  apps/owner/src/pages/MyPage/components/ReviewList.tsx
  apps/owner/src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  apps/owner/src/pages/ReviewDetailPage/components/EditDeleteModal.tsx
  apps/owner/src/pages/ReviewDetailPage/swiperStyle.css
  apps/owner/src/router.tsx
  packages/design-system/components/Header/Header.tsx
  packages/design-system/components/Icons/BookmarkFillIcon.tsx
  packages/design-system/components/Icons/BookmarkIcon.tsx
  packages/design-system/components/Icons/CloseIcon.tsx
  packages/design-system/components/Icons/EmptyHeartIcon.tsx
  packages/design-system/components/Icons/FilledHeartIcon.tsx
  packages/design-system/components/Icons/LockIcon.tsx
  packages/design-system/components/Icons/MoreIcon.tsx
  packages/design-system/components/Icons/StarEmptyIcon.tsx
  packages/design-system/components/Icons/StarFullIcon.tsx
  packages/design-system/components/Icons/StarHalfIcon.tsx
  packages/design-system/components/Icons/right.svg
  packages/design-system/components/Input/Input.tsx
  packages/design-system/components/ProfileImage/UserProfileImage.tsx
  packages/design-system/components/TypeTwoButton/TypeTwoButton.tsx
  packages/design-system/index.ts
  yarn.lock
Labels: 🛠️ 기능

#52 APIClient -> Shared로 이동
  packages/shared/src/apis/APIClient.ts
  packages/shared/src/apis/APIFetch.ts
  packages/shared/src/apis/HTTPError.ts
  packages/shared/src/constants/api.ts
  packages/shared/src/utils/buildURL.ts
Labels: 🚀 개선

#54 타입에러에 대한 수정
  .yarn/install-state.gz
  apps/owner/package.json
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Status/DetailPage.tsx
  apps/owner/src/pages/Suggest/Suggest.tsx
  apps/owner/src/pages/Suggest/TextEditor.tsx
  apps/owner/src/quill.d.ts
  apps/owner/src/router.tsx
  apps/owner/src/styles/TextEditor.css
  apps/owner/src/types/requestAndStatusTypes.ts
  packages/design-system/components/TypeOneButton/TypeOneButton.tsx
  yarn.lock
Labels: 🐞 버그

#59 하단 탭 바 개선 및 스와이퍼 css 중복 문제 해결
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  apps/owner/src/pages/ReviewDetailPage/swiperStyle.css
  apps/owner/src/stores/bottomTabStore.tsx
  packages/design-system/components/FileUploader/ImageSlider.tsx
  packages/design-system/components/FileUploader/swiperStyles.css
Labels: 🚀 개선

#57 designer vite.config.js 수정
  apps/designer/vite.config.ts
Labels: 🍪 배포

#60 메인 페이지 UI 구현
  .yarn/install-state.gz
  apps/owner/package.json
  apps/owner/src/assets/images/MainCategoryTab/map.png
  apps/owner/src/assets/images/MainCategoryTab/popular.png
  apps/owner/src/assets/images/MainCategoryTab/premium.png
  apps/owner/src/assets/images/MainCategoryTab/total.png
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/components/DesignerInfo/Designer.tsx
  apps/owner/src/components/DesignerInfo/DesignerData.ts
  apps/owner/src/components/DesignerInfo/DesignerList.tsx
  apps/owner/src/components/DesignerInfo/PopularList.tsx
  apps/owner/src/components/DesignerInfo/PremiumList.tsx
  apps/owner/src/components/DesignerInfo/TotalList.tsx
  apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx
  apps/owner/src/components/NaverMap/CurrentLocationBtn.tsx
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/MainPage/MainPage.tsx
  apps/owner/src/pages/MainPage/SearchResultPage.tsx
  apps/owner/src/pages/Map/MapPage.tsx
  apps/owner/src/router.tsx
  apps/owner/src/stores/designerListStore.tsx
  packages/design-system/components/Icons/BookMark/EmptyBookMarkIcon.tsx
  packages/design-system/components/Icons/BookMark/FullBookMarkIcon.tsx
  packages/design-system/components/Icons/Star/EmptyStarIcon.tsx
  packages/design-system/components/Icons/Star/FullStarIcon.tsx
  packages/design-system/components/Icons/Star/HalfStarIcon.tsx
  packages/design-system/components/SearchBar/SearchBar.tsx
  packages/design-system/index.ts
  yarn.lock
Labels: 🛠️ 기능

#61 예약 및 미용 완료 내역 조회 페이지 구현
  .yarn/install-state.gz
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/MyPage/components/Profile.tsx
  apps/owner/src/pages/ReservationPage/ReservationPage.tsx
  apps/owner/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/owner/src/pages/ReservationPage/components/ReservationHistory.tsx
  apps/owner/src/router.tsx
  packages/design-system/components/Buttons/MiniButton.tsx
  packages/design-system/components/Icons/BulbIcon.tsx
  packages/design-system/components/Icons/ScissorIcon.tsx
  packages/design-system/index.ts
  yarn.lock
Labels: 🛠️ 기능

#62 리뷰 작성 페이지 추가 및 전체 스타일 수정
  .yarn/install-state.gz
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
  apps/owner/src/pages/CreateReviewPage/CreateReviewPage.tsx
  apps/owner/src/pages/EditPetProfilePage/EditPetProfilePage.tsx
  apps/owner/src/pages/EditUserProfilePage/EditUserProfilePage.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Status/DetailPage.tsx
  apps/owner/src/pages/Suggest/Suggest.tsx
  apps/owner/src/router.tsx
  apps/storybook/src/stories/ImageSlider.stories.tsx
  apps/storybook/src/stories/Star.stories.tsx
  apps/storybook/src/stories/StarRating.stories.tsx
  packages/design-system/components/BottomTabBar/BottomTabBar.tsx
  packages/design-system/components/FileUploader/ImageUploader.tsx
  packages/design-system/components/Header/Header.tsx
  packages/design-system/components/Icons/HalfStarIcon.tsx
  packages/design-system/components/Icons/StarIcon.tsx
  packages/design-system/components/StarRating/StarRating.tsx
  packages/design-system/components/TextArea/TextArea.tsx
  packages/design-system/components/TypeOneButton/TypeOneButton.tsx
  packages/design-system/index.ts
  packages/tailwind-config/tailwind.config.js
Labels: 🚀 개선, 🛠️ 기능

#63 디테일페이지 ui 수정
  apps/owner/src/pages/Request/ProfileViewer.tsx
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Status/CompletedRequestUser.tsx
  apps/owner/src/pages/Status/DetailDesigner.tsx
  apps/owner/src/pages/Status/PendingRequestUser.tsx
  apps/owner/src/pages/Status/RequestContainer.tsx
  apps/owner/src/pages/Status/SuggestReview.tsx
  apps/owner/src/pages/Suggest/Suggest.tsx
  apps/owner/src/pages/Suggest/TextEditor.tsx
  apps/owner/src/router.tsx
  packages/design-system/components/Calendar/Calendar.tsx
Labels: 🚀 개선

#64 지도 marker 추가 및 사용자 위치 획득
  .yarn/install-state.gz
  apps/designer/src/constrants/routes.ts
  apps/guardian/src/constrants/routes.ts
  apps/owner/package.json
  apps/owner/src/components/NaverMap/CustomMarker.tsx
  apps/owner/src/pages/Map/MapPage.tsx
  apps/owner/src/types/maps.ts
  apps/storybook/src/stories/Header.stories.tsx
  packages/design-system/components/Header/Header.tsx
  packages/design-system/components/Icons/BackIcon.tsx
  packages/design-system/components/Icons/BellAlertIcon.tsx
  packages/design-system/components/Icons/BellIcon.tsx
  packages/design-system/components/Icons/CircleScissorIcon.tsx
  packages/design-system/components/Icons/CloseIcon.tsx
  packages/design-system/components/Icons/StarEmptyIcon.tsx
  packages/design-system/components/Icons/StarFullIcon.tsx
  packages/design-system/components/Icons/StarHalfIcon.tsx
  packages/design-system/components/Icons/toast/ConfirmIcon.tsx
  packages/design-system/components/Icons/toast/ErrorIcon.tsx
  packages/design-system/components/Icons/toast/WarningIcon.tsx
  packages/design-system/index.ts
  packages/shared/src/hooks/useUserLocation.ts
  packages/shared/src/index.ts
Labels: 🛠️ 기능

#67 서비스마다 console.log 추가
  apps/designer/src/App.tsx
  apps/designer/src/constants/routes.ts
  apps/designer/src/router.tsx
  apps/guardian/src/App.tsx
  apps/guardian/src/constants/routes.ts
  apps/guardian/src/router.tsx
Labels: 🍪 배포

#69 로그인/회원가입 UI 초기 구현 및 공통 컴포넌트 디자인 수정
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/components/DesignerInfo/Designer.tsx
  apps/owner/src/components/DesignerInfo/DesignerList.tsx
  apps/owner/src/components/KakaoLoginBtn/KakaoIcon.tsx
  apps/owner/src/components/KakaoLoginBtn/KakaoLoginBtn.tsx
  apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/EditUserProfilePage/EditUserProfilePage.tsx
  apps/owner/src/pages/LoginPage/LoginContent.tsx
  apps/owner/src/pages/LoginPage/LoginPage.tsx
  apps/owner/src/pages/MainPage/MainPage.tsx
  apps/owner/src/pages/SignUp/SignUpPage.tsx
  apps/owner/src/router.tsx
  packages/design-system/components/Header/Header.tsx
  packages/design-system/components/TypeTwoButton/TypeTwoButton.tsx
Labels: 🚀 개선, 🛠️ 기능

#71 카테고리 탭 바 및 아바타 스타일 수정
  .yarn/install-state.gz
  packages/design-system/components/Avatar/Avatar.tsx
  packages/design-system/components/CategoryTab/CategoryTab.tsx
Labels: 🚀 개선

#72 guardian 서비스 test 페이지 추가
  apps/guardian/src/constants/routes.ts
  apps/guardian/src/router.tsx
Labels: 🍪 배포

#73 레이아웃 대폭 수정
  apps/owner/src/pages/Request/ProfileViewer.tsx
  apps/owner/src/pages/Request/Request.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Status/CompletedRequestDesigner.tsx
  apps/owner/src/pages/Status/CompletedRequestUser.tsx
  apps/owner/src/pages/Status/DetailDesigner.tsx
  apps/owner/src/pages/Status/DetailPage.tsx
  apps/owner/src/pages/Status/PendingRequestDesigner.tsx
  apps/owner/src/pages/Status/PendingRequestReservation.tsx
  apps/owner/src/pages/Status/PendingRequestUser.tsx
  apps/owner/src/pages/Status/Status.tsx
  apps/owner/src/pages/Status/SuggestReview.tsx
  apps/owner/src/pages/Suggest/Suggest.tsx
  packages/design-system/components/BorderContainer/BorderContainer.tsx
Labels: 🚀 개선

#74 guardian, designer router basename 추가
  .yarn/install-state.gz
  apps/designer/src/router.tsx
  apps/guardian/src/router.tsx
Labels: 🍪 배포

#75 견적 페이지 전체 구현
  apps/designer/src/pages/StatusPage/dummt.tsx
  apps/designer/src/types/designerRequestAndStatusTypes.ts
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Status/CompletedRequest.tsx
  apps/owner/src/pages/Status/CompletedRequestDesigner.tsx
  apps/owner/src/pages/Status/CompletedRequestUser.tsx
  apps/owner/src/pages/Status/DetailDesigner.tsx
  apps/owner/src/pages/Status/DetailPage.tsx
  apps/owner/src/pages/Status/PendingRequestDesigner.tsx
  apps/owner/src/pages/Status/PendingRequestUser.tsx
  apps/owner/src/pages/Status/Status.tsx
  apps/owner/src/pages/Status/SuggestReview.tsx
  apps/owner/src/pages/Suggest/Suggest.tsx
  apps/owner/src/router.tsx
  apps/owner/tsconfig.app.json
  packages/design-system/components/Header/Header.tsx
  packages/design-system/components/Notification/Notification.tsx
  packages/design-system/components/Progress/progress.tsx
  packages/design-system/components/RegionSelector/RegionSelector.tsx
  packages/design-system/components/TypeTwoButton/TypeTwoButton.tsx
Labels: 🚀 개선, 🛠️ 기능

#79 빌드 에러 수정
  apps/designer/src/pages/EditDesignerProfilePage/EditDesignerProfilePage.tsx
  apps/designer/src/pages/MyPage/components/ReviewList.tsx
  apps/designer/src/pages/ReviewDetailPage/ReviewDetailPage.tsx
Labels: 🐞 버그

#80 알림용 아이콘 추가 및 알림 디자인 구현
  .yarn/install-state.gz
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/router.tsx
  packages/design-system/components/Icons/ExclamationIcon.tsx
  packages/design-system/components/Icons/exclamation-circle.svg
  packages/design-system/components/Notification/Notification.tsx
  packages/design-system/index.ts
  packages/shared/src/components/Notification/FullNotification.tsx
  packages/shared/src/components/Notification/Notification.tsx
  packages/shared/src/components/Notification/UnreadNotification.tsx
  packages/shared/src/index.ts
Labels: 🛠️ 기능

#82 빌드 에러 수정
  apps/designer/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/designer/src/pages/ReservationPage/components/ReservationHistory.tsx
  apps/owner/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/owner/src/pages/ReservationPage/components/ReservationHistory.tsx
Labels: 🐞 버그

#83 로그인 api 추가 및 예시코드 작성
  apps/designer/src/router.tsx
  apps/owner/.gitignore
  apps/owner/src/apis/login/getLogin.tsx
  apps/owner/src/apis/request/.gitkeep
  apps/owner/src/apis/review/.gitkeep
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/components/KakaoLoginBtn/KakaoLoginBtn.tsx
  apps/owner/src/constants/queryKeys.ts
  apps/owner/src/constants/routes.ts
  apps/owner/src/hooks/queries/Alarm/usePostExample.ts
  apps/owner/src/hooks/queries/Login/useGetLogin.ts
  apps/owner/src/pages/CreateReviewPage/CreateReviewPage.tsx
  apps/owner/src/pages/KakaoCallback/KakaoCallback.tsx
  apps/owner/src/pages/LoginPage/LoginContent.tsx
  apps/owner/src/router.tsx
  apps/owner/vite.config.ts
  packages/shared/src/apis/APIFetch.ts
  packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx
  packages/shared/src/index.ts
Labels: 🛠️ 기능

#84 github action env 설정 및 modal onClose 수정
  .github/workflows/frontend-ci-cd.yml
  apps/storybook/src/stories/assets/discord.svg
  apps/storybook/src/stories/assets/tutorials.svg
  packages/design-system/components/Modal/ModalContainer.tsx
Labels: 🍪 배포, 🛠️ 기능

#88 localhost https 설정
  apps/owner/src/pages/KakaoCallback/KakaoCallback.tsx
  apps/owner/vite.config.ts
  packages/design-system/components/Icons/BookMark/EmptyBookMarkIcon.tsx
  packages/design-system/components/Icons/BookMark/FullBookMarkIcon.tsx
  packages/design-system/components/Icons/BookmarkFillIcon.tsx
  packages/design-system/components/Icons/BookmarkIcon.tsx
  packages/design-system/components/Icons/CloseCircleIcon.tsx
  packages/design-system/components/Icons/InfoIcon.tsx
  packages/design-system/components/Icons/Star/EmptyStarIcon.tsx
  packages/design-system/components/Icons/Star/FullStarIcon.tsx
  packages/design-system/components/Icons/Star/HalfStarIcon.tsx
Labels: 🐞 버그

#90 빌드 에러 수정
  .yarn/install-state.gz
  apps/designer/src/components/BottomTabBar/DesignerBottomTabBar.tsx
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/AddressTest/AddressTest.tsx
  apps/owner/src/pages/EditPetProfilePage/EditPetProfilePage.tsx
  apps/owner/src/pages/Signup1/SignupPage1.tsx
  apps/owner/src/pages/Signup1/SignupSuccessPage.tsx
  apps/owner/src/router.tsx
  packages/design-system/components/DetailButton/DetailButton.tsx
  packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx
Labels: 🐞 버그

#91 디자이너앱 빌드 에러 수정
  apps/designer/src/pages/EditDesignerProfilePage/EditDesignerProfilePage.tsx
  packages/design-system/components/ServiceCheckBox/ServiceCheckBox.tsx
Labels: 🐞 버그

#92 breedList 파일 constants로 이동
  apps/owner/src/constants/breedList.ts
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
Labels: 🚀 개선

#93 디자이너 조회 API 연동
  apps/owner/src/apis/searchDesigner/getSearchResult.ts
  apps/owner/src/apis/searchDesigner/getTotalDesigner.ts
  apps/owner/src/components/DesignerInfo/Designer.tsx
  apps/owner/src/components/DesignerInfo/DesignerData.ts
  apps/owner/src/components/DesignerInfo/DesignerList.tsx
  apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx
  apps/owner/src/constants/queryKeys.ts
  apps/owner/src/hooks/queries/DesignerList/useGetTotalDesigners.ts
  apps/owner/src/pages/MainPage/SearchResultPage.tsx
  packages/design-system/components/Icons/Star/FullStarIcon.tsx
Labels: 🛠️ 기능

#94 네이버 지도 marker 및 windowInfo 추가
  .yarn/install-state.gz
  apps/designer/.gitignore
  apps/owner/eslint.config.js
  apps/owner/index.html
  apps/owner/package.json
  apps/owner/src/apis/home/getHomeMap.ts
  apps/owner/src/components/NaverMap/CurrentLocationBtn.tsx
  apps/owner/src/components/NaverMap/CustomMarker.tsx
  apps/owner/src/components/NaverMap/DesignerInfoWindow.tsx
  apps/owner/src/components/NaverMap/DesignerMarker.tsx
  apps/owner/src/components/NaverMap/Marker.tsx
  apps/owner/src/components/NaverMap/MyMarker.tsx
  apps/owner/src/components/NaverMap/NaverMapContent.tsx
  apps/owner/src/components/NaverMap/RefreshDesignerMarkerButton.tsx
  apps/owner/src/components/NaverMap/UserLocationButton.tsx
  apps/owner/src/hooks/loadNaverMapsScript.ts
  apps/owner/src/hooks/queries/Home/useGetMap.ts
  apps/owner/src/hooks/queries/Login/useGetUserInfo.ts
  apps/owner/src/pages/DesignerProfilePage/DesignerProfilePage.tsx
  apps/owner/src/pages/Map/MapPage.tsx
  apps/owner/src/pages/ProgressPage/IsGuardianProgress/GuardianContent.tsx
  apps/owner/src/router.tsx
  apps/owner/src/types/api.ts
  packages/design-system/components/Icons/CircleScissorIcon.tsx
  packages/design-system/components/Icons/MyLocationIcon.tsx
  packages/design-system/components/Icons/RefreshIcon.tsx
  packages/design-system/components/Icons/Star/FullStarIcon.tsx
  packages/design-system/components/TypeTwoButton/TypeTwoButton.tsx
  packages/design-system/index.ts
  packages/shared/src/hooks/useUserLocation.ts
  packages/shared/src/index.ts
  packages/shared/tsconfig.app.json
  packages/tailwind-config/tailwind.config.js
  yarn.lock
Labels: 🛠️ 기능

#95 메인페이지 디자이너 검색 api 연동
  apps/owner/src/apis/searchDesigner/getSearchResult.ts
  apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx
  apps/owner/src/constants/queryKeys.ts
  apps/owner/src/hooks/queries/DesignerList/useGetSearchDesigners.ts
  apps/owner/src/hooks/queries/DesignerList/useGetTotalDesigners.ts
  apps/owner/src/pages/MainPage/MainPage.tsx
  apps/owner/src/pages/MainPage/SearchResultPage.tsx
Labels: 🛠️ 기능

#98 보호자 프로필 조회/보호자 및 반려견 프로필 상세/예약 내역 조회
  apps/owner/src/apis/designerProfile/getDesignerProfile.tsx
  apps/owner/src/apis/petProfile/getPetProfileDetail.tsx
  apps/owner/src/apis/profile/getBookmark.tsx
  apps/owner/src/apis/profile/getProfile.tsx
  apps/owner/src/apis/profile/getProfileDetail.tsx
  apps/owner/src/apis/profile/updateProfile.tsx
  apps/owner/src/apis/reservation/getReservations.tsx
  apps/owner/src/constants/queryKeys.ts
  apps/owner/src/constants/routes.ts
  apps/owner/src/hooks/queries/CustomerProfile/useGetBookmark.ts
  apps/owner/src/hooks/queries/CustomerProfile/useGetProfile.ts
  apps/owner/src/hooks/queries/CustomerProfile/useGetProfileDetail.ts
  apps/owner/src/hooks/queries/CustomerProfile/useUpdateProfile.ts
  apps/owner/src/hooks/queries/DesignerProfile/useGetDesignerProfile.ts
  apps/owner/src/hooks/queries/PetProfile/useGetPetProfileDetail.ts
  apps/owner/src/hooks/queries/Reservation/useGetReservation.ts
  apps/owner/src/pages/DesignerProfilePage/DesignerProfilePage.tsx
  apps/owner/src/pages/DesignerProfilePage/components/Profile.tsx
  apps/owner/src/pages/DesignerProfilePage/components/ReviewList.tsx
  apps/owner/src/pages/EditPetProfilePage/EditPetProfilePage.tsx
  apps/owner/src/pages/EditUserProfilePage/EditUserProfilePage.tsx
  apps/owner/src/pages/MyPage/MyPage.tsx
  apps/owner/src/pages/MyPage/components/BookmarkItem.tsx
  apps/owner/src/pages/MyPage/components/BookmarkList.tsx
  apps/owner/src/pages/MyPage/components/ReviewList.tsx
  apps/owner/src/pages/ReservationPage/ReservationPage.tsx
  apps/owner/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/owner/src/pages/ReservationPage/components/ReservationHistory.tsx
  packages/design-system/components/FileUploader/ProfileImgUploader.tsx
  packages/design-system/components/Icons/BookmarkFillIcon.tsx
  packages/design-system/components/Icons/BookmarkIcon.tsx
  packages/shared/src/index.ts
Labels: 🛠️ 기능

#100 빌드 에러 수정
  .yarn/install-state.gz
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
  apps/owner/src/pages/DesignerProfilePage/DesignerProfilePage.tsx
  apps/owner/src/pages/DesignerProfilePage/components/ReviewList.tsx
  apps/owner/src/pages/InputTest/InputTest.tsx
  apps/owner/src/router.tsx
Labels: 🐞 버그

#101 네이버 지도 마커 ,windowInfo 및 가디언 위치 정보 웹소켓 통신 추가
  apps/guardian/.gitignore
  apps/guardian/eslint.config.js
  apps/guardian/index.html
  apps/guardian/package.json
  apps/guardian/src/main.tsx
  apps/guardian/src/pages/ProgressPage/ProgressPage.tsx
  apps/guardian/src/router.tsx
  apps/guardian/tsconfig.app.json
  apps/guardian/vite.config.ts
  apps/owner/src/components/NaverMap/LocationButton.tsx
  apps/owner/src/components/NaverMap/NaverGuardianMap.tsx
  apps/owner/src/components/NaverMap/NaverSearchDesignerMap.tsx
  apps/owner/src/main.tsx
  apps/owner/src/pages/Map/MapPage.tsx
  apps/owner/src/pages/ProgressPage/IsGuardianProgress/GuardianContent.tsx
  apps/owner/tsconfig.app.json
  eslint.config.js
  packages/design-system/components/Icons/guardianIcon.tsx
  packages/design-system/index.ts
  packages/shared/eslint.config.js
  packages/shared/src/apis/APISocket.ts
  packages/shared/src/apis/websocket/guardianlocationWebSocket.ts
  packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx
  packages/shared/src/hooks/useInitNavermap.ts
  packages/shared/src/hooks/useWatchUserLocation.ts
  packages/shared/src/index.ts
  packages/shared/src/utils/debounce.ts
  packages/shared/tsconfig.app.json
  yarn.lock
Labels: 🛠️ 기능

#103 vite plugin 수정
  .yarn/install-state.gz
  apps/designer/package.json
  apps/designer/vite.config.ts
  apps/guardian/package.json
  apps/guardian/vite.config.ts
  yarn.lock
Labels: 🐞 버그, 🍪 배포

#105 로그인 상태 관리 및 로그인 여부에 따라 접근 제한 페이지 설정
  .yarn/install-state.gz
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/components/KakaoLoginBtn/KakaoLoginBtn.tsx
  apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx
  apps/owner/src/components/NaverMap/LocationButton.tsx
  apps/owner/src/components/RouteGuard/PrivateWrapper.tsx
  apps/owner/src/components/RouteGuard/PublicRoute.tsx
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/DesignerProfilePage/components/Profile.tsx
  apps/owner/src/pages/KakaoCallback/KakaoCallback.tsx
  apps/owner/src/pages/LoginPage/LoginContent.tsx
  apps/owner/src/pages/Map/MapPage.tsx
  apps/owner/src/pages/MyPage/components/Profile.tsx
  apps/owner/src/router.tsx
  apps/owner/src/stores/useDesignerIdStore.tsx
  apps/owner/src/stores/useOwnerIdStore.tsx
Labels: 🛠️ 기능

#106 알림 sse 추가
  apps/designer/package.json
  apps/guardian/package.json
  apps/owner/src/constants/routes.ts
  apps/owner/src/pages/ReservationPage/ReservationPage.tsx
  apps/owner/src/pages/ReservationPage/components/ReservationHistory.tsx
  apps/owner/src/router.tsx
  packages/design-system/components/Header/BellIconButton.tsx
  packages/design-system/components/Header/Header.tsx
  packages/design-system/components/Modal/Modal.tsx
  packages/design-system/components/Modal/ModalContainer.tsx
  packages/design-system/package.json
  packages/shared/package.json
  packages/shared/src/apis/SSE/SSEEventSource.ts
  packages/shared/src/index.ts
  yarn.lock
Labels: 🍪 배포, 🛠️ 기능

#108 root에 vite 설치
  .yarn/install-state.gz
  package.json
  yarn.lock
Labels: 🐞 버그, 🍪 배포

#110 불필요한 의존성 삭제
  .yarn/install-state.gz
  apps/designer/package.json
  apps/guardian/package.json
  apps/guardian/vite.config.ts
  yarn.lock
Labels: 🚀 개선, 🍪 배포

#111 로그인 여부 상관없이 모든 페이지 접근 가능하도록 임시설정
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/router.tsx
Labels: 🚀 개선

#114 보호자 회원가입 api 연동
  .yarn/install-state.gz
  apps/designer/src/pages/Signup/SignupPage.tsx
  apps/owner/src/apis/signup/postSignup.ts
  apps/owner/src/hooks/queries/Signup/useSignup.ts
  apps/owner/src/pages/KakaoCallback/KakaoCallback.tsx
  apps/owner/src/pages/Map/MapPage.tsx
  apps/owner/src/pages/Signup/SignupPage.tsx
  apps/owner/src/pages/Signup/SignupSuccessPage.tsx
  apps/owner/src/router.tsx
  packages/design-system/components/SignupForm/SignupForm.tsx
  packages/design-system/components/TypeOneButton/TypeOneButton.tsx
  packages/design-system/components/TypeTwoButton/TypeTwoButton.tsx
Labels: 🛠️ 기능

#115 마이 페이지 리뷰 상세/디자이너 찜하기/리뷰 수정 시 조회 API 추가
  .yarn/install-state.gz
  apps/designer/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/designer/src/pages/ReservationPage/components/ReservationHistory.tsx
  apps/designer/src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  apps/owner/src/apis/designerProfile/getDesignerProfile.tsx
  apps/owner/src/apis/designerProfile/getPortfolioDetail.tsx
  apps/owner/src/apis/profile/getProfile.tsx
  apps/owner/src/apis/profile/updateProfile.tsx
  apps/owner/src/apis/review/getFeed.tsx
  apps/owner/src/apis/review/getReviewDetail.tsx
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/constants/queryKeys.ts
  apps/owner/src/constants/routes.ts
  apps/owner/src/hooks/queries/DesignerProfile/useGetDesignerProfile.ts
  apps/owner/src/hooks/queries/DesignerProfile/useGetPortfolioDetail.ts
  apps/owner/src/hooks/queries/Review/useGetFeed.ts
  apps/owner/src/hooks/queries/Review/useGetReviewDetail.ts
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
  apps/owner/src/pages/DesignerProfilePage/DesignerProfilePage.tsx
  apps/owner/src/pages/DesignerProfilePage/components/Portfolio.tsx
  apps/owner/src/pages/DesignerProfilePage/components/Profile.tsx
  apps/owner/src/pages/DesignerProfilePage/components/ReviewList.tsx
  apps/owner/src/pages/EditPetProfilePage/EditPetProfilePage.tsx
  apps/owner/src/pages/EditReviewPage/EditReviewPage.tsx
  apps/owner/src/pages/EditUserProfilePage/EditUserProfilePage.tsx
  apps/owner/src/pages/FeedPage/FeedPage.tsx
  apps/owner/src/pages/MyPage/MyPage.tsx
  apps/owner/src/pages/MyPage/components/AvartarList.tsx
  apps/owner/src/pages/MyPage/components/BookmarkItem.tsx
  apps/owner/src/pages/MyPage/components/BookmarkList.tsx
  apps/owner/src/pages/MyPage/components/Profile.tsx
  apps/owner/src/pages/MyPage/components/ReviewList.tsx
  apps/owner/src/pages/PortfolioDetailPage/PortfolioDetailPage.tsx
  apps/owner/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/owner/src/pages/ReservationPage/components/ReservationHistory.tsx
  apps/owner/src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  apps/owner/src/router.tsx
  packages/design-system/components/FileUploader/ImageUploader.tsx
  packages/shared/src/index.ts
  packages/shared/src/utils/extractKorean.ts
Labels: 🛠️ 기능

#116 빌드 에러 수정: 사용하지 않는 변수 제거
  apps/owner/src/pages/DesignerProfilePage/components/Profile.tsx
Labels: 🐞 버그

#117 guardian tsconfig 수정
  apps/guardian/tsconfig.app.json
Labels: 🐞 버그, 🍪 배포

#118 견적조회, 견적제안조회 api 연결
  apps/designer/src/apis/request/getCompletedRequest.ts
  apps/designer/src/apis/request/getPendingRequest.ts
  apps/designer/src/apis/request/putSuggest.ts
  apps/designer/src/constants/routes.ts
  apps/designer/src/hooks/queries/Request/usePutSuggest.ts
  apps/designer/src/pages/RequestPage/PastRequestReview.tsx
  apps/designer/src/pages/RequestPage/ProfileViewer.tsx
  apps/designer/src/pages/StatusPage/CompletedRequestDesigner.tsx
  apps/designer/src/pages/StatusPage/DetailPage.tsx
  apps/designer/src/pages/StatusPage/PendingRequest.tsx
  apps/designer/src/pages/StatusPage/PendingRequestDesigner.tsx
  apps/designer/src/pages/SuggestPage/SuggestPage.tsx
  apps/designer/src/router.tsx
  apps/owner/src/apis/request/postCreateBidRequest.ts
  apps/owner/src/apis/requestStatus/postRequestStatus.tsx
  apps/owner/src/apis/suggest/postSuggestRequest.ts
  apps/owner/src/hooks/queries/Suggest/useGetDesignerSuggest.ts
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Status/DetailDesigner.tsx
  apps/owner/src/pages/Status/SuggestReview.tsx
  apps/owner/src/types/api.ts
Labels: 🚀 개선, 🛠️ 기능

#119 버전 수정
  apps/designer/package.json
Labels: 🐞 버그, 🚀 개선

#120 router 버전 통일
  .yarn/install-state.gz
  apps/designer/package.json
  yarn.lock
Labels: 🐞 버그, 🍪 배포

#121 progress page setting
  apps/designer/src/constants/routes.ts
  apps/designer/src/pages/MainPage.tsx
  apps/designer/src/pages/ProgressPage/ProgressPage.tsx
  apps/designer/src/pages/ProgressPage/ProgressStep1.tsx
  apps/designer/src/pages/ProgressPage/ProgressStep2.tsx
  apps/designer/src/pages/ProgressPage/ProgressStep3.tsx
  apps/guardian/src/constants/routes.ts
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep1.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep2and4.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep3.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep5.tsx
  apps/guardian/src/pages/ProgressPage/NaverSendLocationMap.tsx
  apps/guardian/src/pages/ProgressPage/ProgressPage.tsx
  apps/guardian/src/router.tsx
  apps/owner/src/pages/ProgressPage/IsGuardianProgress/IsGuardianProgressPage.tsx
  apps/owner/src/pages/ProgressPage/IsGuardianProgress/ProgressStep1.tsx
  apps/owner/src/pages/ProgressPage/IsGuardianProgress/ProgressStep2and4.tsx
  apps/owner/src/pages/ProgressPage/IsGuardianProgress/ProgressStep3.tsx
  apps/owner/src/pages/ProgressPage/IsGuardianProgress/ProgressStep5.tsx
  apps/owner/src/pages/ProgressPage/IsGuardianProgress/Step1.tsx
  apps/owner/src/pages/ProgressPage/ProgressPage.tsx
  packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx
Labels: 🛠️ 기능

#122 vite root에서 삭제
  .yarn/install-state.gz
  package.json
  yarn.lock
Labels: 🐞 버그

#123 tsconfig 수정
  apps/guardian/src/pages/MainPage.tsx
  apps/guardian/tsconfig.app.json
Labels: 🐞 버그, 🍪 배포

#124 workflow env 추가 및 navermap submodule 추가
  .github/workflows/frontend-ci-cd.yml
  apps/guardian/index.html
Labels: 🍪 배포, 🛠️ 기능

#126 title, 파비콘 추가
  apps/designer/index.html
  apps/designer/public/daeng-ggu.svg
  apps/designer/public/vite.svg
  apps/guardian/index.html
  apps/guardian/public/daeng-ggu.svg
  apps/guardian/public/vite.svg
  apps/owner/index.html
  apps/owner/public/daeng-ggu.svg
  apps/owner/public/vite.svg
Labels: 🛠️ 기능

#127 yarn.lock 수정 및 스토리북 title, 파비콘 설정
  .yarn/install-state.gz
  apps/guardian/src/pages/MainPage.tsx
  apps/storybook/index.html
  apps/storybook/public/daeng-ggu.svg
  yarn.lock
Labels: 🍪 배포, 🛠️ 기능

#128 vite.config base 추가
  apps/designer/vite.config.ts
  apps/guardian/vite.config.ts
Labels: 🐞 버그, 🍪 배포

#129 apiFetch 컴포넌트 헤더 완화
  .yarn/install-state.gz
  apps/owner/package.json
  apps/owner/src/apis/imageUpload/postSingleImageUpload.ts
  apps/owner/src/apis/payment/getPaymentOrderId.ts
  apps/owner/src/constants/routes.ts
  apps/owner/src/hooks/queries/ImageUpload/useSingleImageUpload.ts
  apps/owner/src/hooks/queries/Payment/useGetPaymentDetail.ts
  apps/owner/src/pages/PaymentPage/PaymentPage.tsx
  apps/owner/src/pages/PaymentPage/PaymentSuccessPage.tsx
  apps/owner/src/pages/Request/Test.tsx
  apps/owner/src/pages/Status/SuggestReview.tsx
  apps/owner/src/router.tsx
  apps/owner/src/types/api.ts
  packages/shared/src/apis/APIFetch.ts
  yarn.lock
Labels: 🐞 버그, 🚀 개선, 🛠️ 기능

#130 tsconfig 수정
  apps/guardian/tsconfig.app.json
Labels: 🐞 버그

#132 플러그인 버전 통일
  .yarn/install-state.gz
  apps/owner/package.json
  yarn.lock
Labels: 🐞 버그, 🍪 배포

#133 github action workflow 수정
  .github/workflows/frontend-ci-cd.yml
  apps/guardian/tsconfig.app.json
Labels: 🐞 버그

#135 다중이미지 업로드 api
  apps/owner/src/apis/imageUpload/postMultipleImageUpload.ts
  apps/owner/src/hooks/queries/ImageUpload/useMultipleImageUpload.ts
  apps/owner/src/pages/Request/Test.tsx
Labels: 🚀 개선, 🛠️ 기능

#136 guardian progress 페이지 구현
  apps/guardian/src/apis/monitoring/getMonitoringStatus.ts
  apps/guardian/src/apis/monitoring/getReservationList.ts
  apps/guardian/src/apis/monitoring/postArriveAtHome.ts
  apps/guardian/src/apis/monitoring/postArriveAtShop.ts
  apps/guardian/src/apis/monitoring/postCreateReservationProcess.ts
  apps/guardian/src/apis/monitoring/postStartDeliveryToHome.ts
  apps/guardian/src/apis/monitoring/postStartDeliveryToShop.ts
  apps/guardian/src/components/ReservationCard/ReservationCard.tsx
  apps/guardian/src/constants/api.ts
  apps/guardian/src/constants/breedList.ts
  apps/guardian/src/constants/queryKeys.ts
  apps/guardian/src/constants/routes.ts
  apps/guardian/src/hooks/queries/useGetMonitoringStatus.ts
  apps/guardian/src/hooks/queries/useGetReservationList.ts
  apps/guardian/src/hooks/queries/usePostArriveAtHome.ts
  apps/guardian/src/hooks/queries/usePostArriveAtShop.ts
  apps/guardian/src/hooks/queries/usePostStartDeliveryToHome.ts
  apps/guardian/src/hooks/queries/usePostStartDeliveryToShop.ts
  apps/guardian/src/pages/MainPage.tsx
  apps/guardian/src/pages/MainPage/MainPage.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep1.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep2and4.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep2and6.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep3.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep3and4and5.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep7.tsx
  apps/guardian/src/pages/ProgressPage/NaverSendLocationMap.tsx
  apps/guardian/src/pages/ProgressPage/ProgressPage.tsx
  apps/guardian/src/router.tsx
  apps/guardian/src/types/api.ts
  apps/guardian/src/types/reservation.ts
  packages/design-system/components/Header/Header.tsx
Labels: 🛠️ 기능

#137 디자이너 프로필 등록 API 연동
  .yarn/install-state.gz
  apps/designer/src/apis/Profile/registerProfile.ts
  apps/designer/src/apis/imageUpload/postMultipleImageUpload.ts
  apps/designer/src/apis/imageUpload/postSingleImageUpload.ts
  apps/designer/src/components/BottomTabBar/DesignerBottomTabBar.tsx
  apps/designer/src/components/PriceAndTime/PriceAndTime.tsx
  apps/designer/src/constants/routes.ts
  apps/designer/src/hooks/queries/ImageUpload/useMultipleImageUpload.ts
  apps/designer/src/hooks/queries/ImageUpload/useSingleImageUpload.ts
  apps/designer/src/hooks/queries/Profile/useRegisterProfile.ts
  apps/designer/src/pages/AddPortfolioPage/AddPortfolioInRegister.tsx
  apps/designer/src/pages/AddPortfolioPage/AddPortfolioPage.tsx
  apps/designer/src/pages/RegisterProfile/RegisterProfileData.tsx
  apps/designer/src/pages/RegisterProfile/RegisterStep.tsx
  apps/designer/src/pages/RegisterProfile/Step1.tsx
  apps/designer/src/pages/RegisterProfile/Step2.tsx
  apps/designer/src/pages/RegisterProfile/Step3.tsx
  apps/designer/src/pages/RegisterProfile/Step4.tsx
  apps/designer/src/stores/bottomTabStore.tsx
  apps/designer/src/stores/useProfileStore.tsx
  apps/owner/src/apis/login/getLogin.ts
  apps/owner/src/pages/Signup/SignupPage.tsx
  apps/owner/src/pages/Signup/SignupSuccessPage.tsx
  packages/design-system/components/DogTypePicker/DogTypePicker.tsx
  packages/design-system/components/DropdownCheckBox/DropdownCheckBox.tsx
  packages/design-system/components/FileUploader/ImageUploader.tsx
  packages/design-system/components/FileUploader/ProfileImgUploader.tsx
  packages/design-system/components/Input/Input.tsx
  packages/design-system/components/InputAddress/SearchAddress.tsx
  packages/design-system/components/ServiceCheckBox/ServiceCheckBox.tsx
Labels: 🛠️ 기능

#139 반려견 등록 api 연동
  apps/designer/src/hooks/queries/Profile/useRegisterProfile.ts
  apps/owner/src/apis/petProfile/registerPetProfile.ts
  apps/owner/src/hooks/queries/PetProfile/useRegisterPetProfile.ts
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
  apps/owner/src/pages/KakaoCallback/KakaoCallback.tsx
Labels: 🛠️ 기능

#140 메인페이지에서 디자이너 프로필로 연결
  apps/owner/src/components/DesignerInfo/Designer.tsx
  apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx
Labels: 🛠️ 기능

#142 인자 제거
  apps/owner/src/pages/ReservationPage/ReservationPage.tsx
Labels: 🐞 버그

#144 빌드 에러 수정
  apps/designer/src/pages/ReservationPage/ReservationPage.tsx
Labels: 🐞 버그

#149 빌드 에러 수정 및 수수료 문구 추가
  .yarn/install-state.gz
  apps/designer/src/pages/EditDesignerProfilePage/EditDesignerProfilePage.tsx
  apps/designer/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/designer/src/pages/ReservationPage/components/ReservationHistory.tsx
  apps/owner/src/hooks/queries/Image/usePostImage.ts
  apps/owner/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/owner/src/pages/ReservationPage/components/ReservationHistory.tsx
  packages/design-system/components/FileUploader/ImageUploader.tsx
Labels: 🐞 버그

#151 견적요청 및 예약 초안
  apps/designer/src/apis/request/putSuggest.ts
  apps/designer/src/components/BottomTabBar/DesignerBottomTabBar.tsx
  apps/designer/src/hooks/queries/ImageUpload/useMultipleImageUpload.ts
  apps/designer/src/hooks/queries/Request/usePostDetailPage.ts
  apps/designer/src/hooks/queries/Request/usePutSuggest.ts
  apps/designer/src/pages/StatusPage/DetailPage.tsx
  apps/designer/src/pages/SuggestPage/SuggestPage.tsx
  apps/owner/src/apis/payment/getPaymentOrderId.ts
  apps/owner/src/apis/payment/postPaymentProcess.ts
  apps/owner/src/apis/payment/postReservationEstimate.ts
  apps/owner/src/apis/suggest/postSuggestRequest.ts
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/hooks/queries/Payment/useGetPaymentDetail.ts
  apps/owner/src/hooks/queries/Payment/useGetPaymentProcess.ts
  apps/owner/src/hooks/queries/Payment/usePostReservationEstimate.ts
  apps/owner/src/hooks/queries/Request/useGetPendingRequests.ts
  apps/owner/src/hooks/queries/Request/useGetUserCompletedRequests.ts
  apps/owner/src/pages/DirectRequestPage/DirectRequestPage.tsx
  apps/owner/src/pages/PaymentPage/PaymentPage.tsx
  apps/owner/src/pages/PaymentPage/PaymentSuccessPage.tsx
  apps/owner/src/pages/Request/ProfileViewer.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/Status/DetailPage.tsx
  apps/owner/src/pages/Status/PendingRequestUser.tsx
  apps/owner/src/pages/Status/Status.tsx
  apps/owner/src/pages/Status/SuggestReview.tsx
  apps/owner/src/stores/usePaymentStore.ts
  apps/owner/src/stores/useReservationStoreOne.ts
  apps/owner/src/stores/useReservationStoreTwo.ts
Labels: 🚀 개선, 🛠️ 기능

#152 반려견 수정 api 연동
  apps/owner/src/pages/EditPetProfilePage/EditPetProfilePage.tsx
  packages/design-system/components/Avatar/Avatar.tsx
  packages/design-system/components/ProfileImage/UserProfileImage.tsx
Labels: 🛠️ 기능

#155 import 경로 수정
  .yarn/install-state.gz
  packages/shared/src/components/Notification/FullNotification.tsx
  packages/shared/src/components/Notification/UnreadNotification.tsx
  packages/shared/src/hooks/queries/useGetAlarms.ts
Labels: 🐞 버그, 🍪 배포

#156 v1.1.1 Release
  .yarn/install-state.gz
  packages/shared/src/components/Notification/FullNotification.tsx
  packages/shared/src/components/Notification/UnreadNotification.tsx
  packages/shared/src/hooks/queries/useGetAlarms.ts
Labels: 🐞 버그, 🍪 배포

#157 디자이너 사업자 인증 API 연동
  apps/designer/src/apis/verifyBusiness/verifyBusiness.ts
  apps/designer/src/constants/queryKeys.ts
  apps/designer/src/hooks/queries/VerifyBusiness/useVerifyBusiness.ts
  apps/designer/src/pages/RegisterProfile/RegisterStep.tsx
  apps/designer/src/pages/RegisterProfile/Step3.tsx
  apps/designer/src/pages/RegisterProfile/Step4.tsx
  apps/designer/src/stores/useProfileStore.tsx
  apps/guardian/src/App.tsx
  apps/owner/src/pages/Signup/SignupSuccessPage.tsx
Labels: 🛠️ 기능

#161 디자이너 프로필 수정 api 연동
  apps/designer/src/apis/Profile/updateProfile.ts
  apps/designer/src/components/BottomTabBar/DesignerBottomTabBar.tsx
  apps/designer/src/pages/EditDesignerProfilePage/EditDesignerProfilePage.tsx
  apps/designer/src/pages/EditDesignerProfilePage/components/CertificationUploader.tsx
  apps/designer/src/pages/MyPage/components/Profile.tsx
  apps/designer/src/pages/ReservationPage/ReservationPage.tsx
  packages/design-system/components/ServiceCheckBox/ServiceCheckBox.tsx
Labels: 🛠️ 기능

#162 notfound 및 privateWrapper 추가
  apps/designer/src/components/RouteGuard/PrivateWrapper.tsx
  apps/designer/src/router.tsx
  apps/guardian/src/constants/routes.ts
  apps/guardian/src/router.tsx
  apps/owner/src/components/RouteGuard/PrivateWrapper.tsx
  apps/owner/src/hooks/queries/Home/useGetMap.ts
  apps/owner/src/router.tsx
  packages/shared/src/apis/APIFetch.ts
  packages/shared/src/components/NotFound/NotFound.tsx
  packages/shared/src/components/PrivateWrapper/PrivateWrapper.tsx
  packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx
  packages/shared/src/index.ts
Labels: 🍪 배포, 🛠️ 기능

#164 진행 단계 spinner 추가
  apps/designer/src/constants/progress.ts
  apps/designer/src/pages/ProgressPage/ProgressPage.tsx
  apps/designer/src/pages/ProgressPage/ProgressStep1.tsx
  apps/designer/src/pages/ProgressPage/ProgressStep2.tsx
  apps/guardian/src/hooks/queries/usePostStartDeliveryToShop.ts
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep1.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep2and6.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep3and4and5.tsx
  apps/owner/src/apis/request/.gitkeep
  apps/owner/src/apis/review/.gitkeep
  packages/design-system/components/TypeTwoButton/TypeTwoButton.tsx
  packages/shared/src/components/Spinner/Spinner.tsx
  packages/shared/src/index.ts
Labels: 🛠️ 기능

#165 v1.1.2 Release
  apps/designer/src/constants/progress.ts
  apps/designer/src/pages/ProgressPage/ProgressPage.tsx
  apps/designer/src/pages/ProgressPage/ProgressStep1.tsx
  apps/designer/src/pages/ProgressPage/ProgressStep2.tsx
  apps/guardian/src/hooks/queries/usePostStartDeliveryToShop.ts
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep1.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep2and6.tsx
  apps/guardian/src/pages/ProgressPage/GuardianProgressStep3and4and5.tsx
  apps/owner/src/apis/request/.gitkeep
  apps/owner/src/apis/review/.gitkeep
  packages/design-system/components/TypeTwoButton/TypeTwoButton.tsx
  packages/shared/src/components/Spinner/Spinner.tsx
  packages/shared/src/index.ts
Labels: 🍪 배포

#166 로그인 에러 처리 추가
  packages/shared/src/apis/APIFetch.ts
  packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx
Labels: 🛠️ 기능

#167 v1.1.3 Release
  packages/shared/src/apis/APIFetch.ts
  packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx
Labels: 🍪 배포

#168 로그아웃 api 연동
  apps/designer/src/apis/review/getFeed.ts
  apps/designer/src/hooks/queries/Review/useGetFeed.ts
  apps/designer/src/router.tsx
  apps/owner/src/apis/login/getLogout.ts
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
  apps/owner/src/pages/MyPage/components/Profile.tsx
  packages/design-system/components/Icons/Location.tsx
Labels: 🛠️ 기능

#169 useQuery로 변경 및 REVIEW_QUERY_KEYS 추가
  apps/designer/src/constants/queryKeys.ts
  apps/designer/src/hooks/queries/Request/useGetCompletedRequest.ts
  apps/designer/src/hooks/queries/Request/useGetPendingRequests.ts
  apps/designer/src/hooks/queries/Request/usePostDetailPage.ts
  apps/designer/src/pages/StatusPage/DetailPage.tsx
  apps/designer/src/pages/StatusPage/PendingRequest.tsx
  apps/designer/src/pages/StatusPage/StatusPage.tsx
  apps/owner/src/hooks/queries/Request/useGetOwnerPetProfile.ts
  apps/owner/src/hooks/queries/Suggest/useGetDesignerSuggest.ts
  apps/owner/src/pages/DirectRequestPage/DirectRequestPage.tsx
  apps/owner/src/pages/Request/Request.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
Labels: 🐞 버그

#172 프로필 생성 버그 수정
  apps/designer/src/pages/AddPortfolioPage/AddPortfolioInProfile.tsx
  apps/designer/src/pages/AddPortfolioPage/AddPortfolioPage.tsx
  apps/designer/src/pages/RegisterProfile/RegisterStep.tsx
  apps/designer/src/pages/RegisterProfile/Step2.tsx
  apps/designer/src/pages/RegisterProfile/Step3.tsx
  apps/designer/src/router.tsx
  apps/owner/src/apis/review/postReviewLike.ts
  apps/owner/src/hooks/queries/Review/usePostReviewLike.ts
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
  apps/owner/src/pages/DirectRequestPage/DirectRequestPage.tsx
  apps/owner/src/pages/FeedPage/FeedPage.tsx
  packages/shared/src/components/PrivateWrapper/PrivateWrapper.tsx
Labels: 🐞 버그

#173 지도에서 디자이너 프로필 이동 수정
  apps/owner/src/components/NaverMap/NaverSearchDesignerMap.tsx
Labels: 🐞 버그

#174 v1.1.5 Release
  apps/owner/src/components/NaverMap/NaverSearchDesignerMap.tsx
Labels: 🍪 배포

#175 UI 수정중
  apps/designer/src/apis/Login/getLogout.ts
  apps/designer/src/pages/FeedPage/FeedPage.tsx
  apps/designer/src/pages/FeedPage/swiperStyle.css
  apps/designer/src/pages/PortfolioDetailPage/swiperStyle.css
  apps/designer/src/pages/RegisterProfile/RegisterStep.tsx
  apps/designer/src/pages/RegisterProfile/Step4.tsx
  apps/designer/src/pages/ReviewDetailPage/swiperStyle.css
  apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx
  apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx
  apps/owner/src/pages/DesignerProfilePage/DesignerProfilePage.tsx
  apps/owner/src/pages/DesignerProfilePage/components/Portfolio.tsx
  apps/owner/src/pages/DesignerProfilePage/components/Profile.tsx
  apps/owner/src/pages/DesignerProfilePage/components/ReviewList.tsx
  apps/owner/src/pages/FeedPage/swiperStyle.css
  apps/owner/src/pages/MyPage/components/Profile.tsx
  packages/design-system/components/Icons/BadgeCheckIcon.tsx
  packages/design-system/components/Icons/MapIcon.tsx
  packages/design-system/components/Icons/ScissorIcon.tsx
  packages/design-system/components/Icons/exclamation-circle.svg
  packages/design-system/index.ts
Labels: 🚀 개선

#176 ui 수정
  .yarn/install-state.gz
  apps/designer/src/pages/EditDesignerProfilePage/EditDesignerProfilePage.tsx
  apps/designer/src/pages/EditPortfolioPage/EditPortfolioPage.tsx
  apps/designer/src/pages/RequestPage/ProfileViewer.tsx
  apps/owner/src/pages/EditUserProfilePage/EditUserProfilePage.tsx
  apps/owner/src/pages/Request/ProfileButton.tsx
  apps/owner/src/pages/Request/ProfileViewer.tsx
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/owner/src/pages/Status/PendingRequestUser.tsx
  apps/owner/src/pages/Status/Status.tsx
  packages/design-system/components/Progress/progress.tsx
  packages/design-system/components/RadioGroup/RadioGroup.tsx
  packages/design-system/components/RegionSelector/RegionSelector.tsx
  packages/design-system/components/TimeSelect/TimeSelect.tsx
  packages/design-system/utils/fomDateTime.ts
Labels: 🚀 개선

#178 UI 수정
  apps/designer/index.html
  apps/designer/src/pages/FeedPage/FeedPage.tsx
  apps/designer/src/pages/MyPage/MyPage.tsx
  apps/designer/src/pages/MyPage/components/Portfolio.tsx
  apps/designer/src/pages/MyPage/components/Profile.tsx
  apps/designer/src/pages/MyPage/components/ReviewList.tsx
  apps/designer/src/pages/ReservationPage/ReservationPage.tsx
  apps/designer/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/designer/src/pages/ReservationPage/components/ReservationHistory.tsx
  apps/designer/src/pages/StatusPage/EmptyState.tsx
  apps/guardian/index.html
  apps/owner/index.html
  apps/owner/src/pages/DesignerProfilePage/DesignerProfilePage.tsx
  apps/owner/src/pages/EditPetProfilePage/EditPetProfilePage.tsx
  apps/owner/src/pages/FeedPage/FeedPage.tsx
  apps/owner/src/pages/MyPage/components/BookmarkItem.tsx
  apps/owner/src/pages/MyPage/components/BookmarkList.tsx
  apps/owner/src/pages/MyPage/components/Profile.tsx
  apps/owner/src/pages/Request/ProfileButton.tsx
  apps/owner/src/pages/Request/ProfileViewer.tsx
  apps/owner/src/pages/Request/RequestReview.tsx
  apps/owner/src/pages/Request/StepByStep.tsx
  apps/owner/src/pages/ReservationPage/ReservationPage.tsx
  apps/owner/src/pages/ReservationPage/components/CompletedServices.tsx
  apps/owner/src/pages/ReservationPage/components/ReservationHistory.tsx
  apps/owner/src/pages/Status/CompletedRequestUser.tsx
  apps/owner/src/pages/Status/EmptyState.tsx
  apps/owner/src/pages/Status/PendingRequest.tsx
  apps/owner/src/pages/Status/PendingRequestUser.tsx
  packages/design-system/components/Icons/BulbIcon.tsx
Labels: 🚀 개선

#180 ui 수정
  apps/designer/src/pages/FeedPage/FeedPage.tsx
  apps/designer/src/pages/MyPage/components/Profile.tsx
  apps/designer/src/pages/StatusPage/StatusPage.tsx
  apps/owner/src/pages/DesignerProfilePage/components/Profile.tsx
  apps/owner/src/pages/FeedPage/FeedPage.tsx
  packages/design-system/components/Toast/Toast.tsx
  packages/shared/src/components/Notification/Notification.tsx
Labels: 🚀 개선

#181 delete Request 추가
  apps/owner/src/apis/request/deleteRequest.ts
  apps/owner/src/apis/request/getPendingRequests.ts
  apps/owner/src/components/NaverMap/LocationButton.tsx
  apps/owner/src/components/NaverMap/RefreshDesignerMarkerButton.tsx
  apps/owner/src/hooks/queries/Request/useCreateBidRequest.ts
  apps/owner/src/hooks/queries/Request/useDeleteRequest.ts
  apps/owner/src/pages/Status/PendingRequestUser.tsx
  apps/owner/src/pages/Status/RequestContainer.tsx
  apps/owner/src/types/requestAndStatusTypes.ts
  packages/design-system/components/Icons/CloseIcon.tsx
  packages/shared/src/components/PrivateWrapper/PrivateWrapper.tsx
Labels: 🛠️ 기능
